services:

  web:
    build: ./docker/web
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ${WEB_ROOT_PATH}:${WEB_WORKING_DIR}
    working_dir: ${WEB_WORKING_DIR}
    ports:
      - ${WEB_PORT}:80

  composer:
    image: composer:latest
    volumes:
      - ${WEB_ROOT_PATH}:/var/www/
    working_dir: ${WEB_WORKING_DIR}
    command: composer install