services:

  mysql:
    image: mysql:5.7
    restart: ${MYSQL_RESTART}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ${MYSQL_PATH}:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      mysql:
        condition: "service_healthy"